spring.application.name=saas-billing-system

spring.datasource.url=jdbc:mysql://localhost:3306/saas_billing_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=prachi@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PhonePe Payment Gateway Sandbox Credentials
phonepe.merchant.id=PGPLAYMERCHANT
phonepe.salt.key=099eb0cd-02cf-4e2a-8aca-3e6c6aff0399
phonepe.salt.index=1
phonepe.api.url=https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/pay
phonepe.status.url=https://api-preprod.phonepe.com/apis/pg-sandbox/pg/v1/status